name: Build Release target

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/openquickjs/quickjs-testing-env:latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure CMake
        run: cmake -G Ninja -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

      - name: Build target
        run: cmake --build ${{github.workspace}}/build --target qjs run-test262 -j 8

      - name: Test
        run: ./bin/qjs -e 'console.log("Hello, World!")'
